config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'welcome#index'
  resources "entries"
  get 'pages/info' 
  get 'welcome/index'
  get 'entries/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    def index
        @entries = Entry.all
      end

    def show
        @entry = Entry.find(params["id"])
    end

    def create
      entry_params = params["entry"].permit("title", "contents")
      entry = Entry.create(entry_params)
      redirect_to(entry_path(entry))
      end

    def edit
      @entry = Entry.find(params["id"])
    end

    def update
      entry_params = params["entry"].permit("title", "contents")
      entry = Entry.find(params["id"])
      entry.update(entry_params)
      redirect_to(entry_path(entry))
    end

    def destroy
      @entry = Entry.find(params["id"])
      @entry.destroy
      redirect_to entry_path, :notice => "Your diary has been deleted"
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
    @entries = Entry.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @entries = Entry.all
    @websites = [
      ["http://railsgirls.com", "Rails Girls"],
      ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
      ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/index.html.slim
- for entry in @entries
  .box
    h2
      = link_to(entry.title, entry_path(entry))
    p
      = entry.date
    p
      = entry.contents

app/views/entries/new.html.slim
= form_for(Entry.new) do |form|
  p
    = form.label("title")
  p
    = form.text_field("title")
  p
    = form.label("contents")
  p
    = form.text_area("contents")
  p
    = form.submit
p
  = link_to("Back to all entries", entries_path)

app/views/entries/show.html.slim
= form_for(@entry) do |form|
  p
    = form.label("title")
  p
    = form.text_field("title")
  p
    = form.label("contents")
  p
    = form.text_area("contents")
  p
    = form.submit
button
  = link_to("Back to all entries", entries_path)

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Diary
    = csrf_meta_tags
    = csp_meta_tag
    link[rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css"]
    link[rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      - if notice
        p.alert.alert-success
          = notice
      - if alert
        p.alert.alert-danger
          = alert
      = yield
    nav.navbar.navbar-default.navbar-fixed-top[role="navigation"]
      .container
        .navbar-header
          button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand[href="/"]
            | The Diary app
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              a[href="/entries/new"]
                | New Diary
            li
              a[href="/pages/info"]
                | Info
          p.navbar-text.pull-right
            - if user_signed_in?
              |  Logged in as 
              strong
                = current_user.email
              | . 
              = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
              |  | 
              = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
            - else
              = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
              |  | 
              = link_to "Login", new_user_session_path, :class => 'navbar-link'
    footer
      .container
        |  Diary 
        = Time.now.year
    script[src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"]
    script[src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"]

app/views/pages/info.html.slim
- for entry in @entries
  .box
    h2= entry.title
    p= entry.date
    p= entry.contents

app/views/welcome/index.html.slim
h1 My Rails Girls Diary
- for entry in @entries
  .box
    h2= link_to(entry.title, entry_path(entry))
    p= entry.date
    p= entry.contents